# Generated by Django 5.2.9 on 2026-01-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_warehouse'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
