# Generated by Django 5.2.9 on 2026-01-07 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0006_transferrequest_transferapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerPromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_promotions_requested', to=settings.AUTH_USER_MODEL)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='warehouses.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='warehouses.staff')),
            ],
        ),
    ]
