# Generated by Django 5.2.9 on 2026-01-15 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0011_lowstockthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
